name: dealdash
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
 

dependencies:
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  conditional_builder_null_safety: ^0.0.6
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_offline: ^4.0.0
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  permission_handler: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.0

  flutter_advanced_switch: ^3.1.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  latlong2: ^0.9.0
  flutter_map: ^6.0.0
  timeago: ^3.2.2
  flutter_secure_storage: ^9.2.2




dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/language_flag/
    - assets/images/home_images/
    - assets/images/home_images/banar/
    - assets/images/home_images/category/
    - assets/images/home_images/cloth/
    - assets/images/home_images/mobile/
    - assets/images/home_images/market/
    - assets/images/home_images/electric/
    - assets/font/

    - assets/images/image_notification/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Alarabiya
      fonts:
        - asset: assets/font/alarabiya.ttf
    #        - asset: fonts/TrajanPro_Bold.ttf
    #          weight: 700
    - family: Aljazeera
      fonts:
        - asset: assets/font/aljazeera.ttf
    - family: Sultan
      fonts:
        - asset: assets/font/sultan_bold.ttf
